// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  IntegrationCard: {
    connect: 'Connect'
    disconnect: 'Disconnect'
    stripe: {
      name: 'Stripe'
      description: 'Connect Stripe to start analyzing your data and gain insights into your customers and revenue.'
    }
  }
}
export default messages
